name: CI

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6


      - name: Setup Nim
        uses: alaviss/setup-nim@0.1.1
        with:
          version: devel
          path: 'nim'

      - name: Nim version
        run: nim --version

      - name: install deps (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install libx11-dev libxft-dev fonts-freefont-ttf fonts-dejavu-core

      - name: Build
        run: nim c -r tests/tester.nim
