name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6


      - name: Setup Nim
        uses: alaviss/setup-nim@0.1.1
        with:
          version: devel
          path: 'nim'

      - name: Nim version
        run: nim --version

      - name: install deps
        run: |
          sudo apt update
          sudo apt install libx11-dev libxft-dev fonts-freefont-ttf fonts-dejavu-core


      - name: Build
        run: nimble install -y
